// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2Lr2VHKEVcObAhpqDdH9WFcbURVMGgw',
    appId: '1:1006888893410:web:1d1fc7c18e0b089bcd17bb',
    messagingSenderId: '1006888893410',
    projectId: 'lawbot-9770e',
    authDomain: 'lawbot-9770e.firebaseapp.com',
    storageBucket: 'lawbot-9770e.appspot.com',
    measurementId: 'G-YMV6TVSWCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OZ4O8pzTuQxaXwRZ6Xcd6eexIBRx1S8',
    appId: '1:1006888893410:android:c4f6861bb08feb42cd17bb',
    messagingSenderId: '1006888893410',
    projectId: 'lawbot-9770e',
    storageBucket: 'lawbot-9770e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxURBJNlorvHqBnDtCA5stzFm0uHXLQxA',
    appId: '1:1006888893410:ios:55f78c90bd05b4b2cd17bb',
    messagingSenderId: '1006888893410',
    projectId: 'lawbot-9770e',
    storageBucket: 'lawbot-9770e.appspot.com',
    iosClientId:
        '1006888893410-to7m9peve3tq7vu26a6j1rl211s2h7cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.inocentesLab6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxURBJNlorvHqBnDtCA5stzFm0uHXLQxA',
    appId: '1:1006888893410:ios:55f78c90bd05b4b2cd17bb',
    messagingSenderId: '1006888893410',
    projectId: 'lawbot-9770e',
    storageBucket: 'lawbot-9770e.appspot.com',
    iosClientId:
        '1006888893410-to7m9peve3tq7vu26a6j1rl211s2h7cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.inocentesLab6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2Lr2VHKEVcObAhpqDdH9WFcbURVMGgw',
    appId: '1:1006888893410:web:e8dee1f988b8eda7cd17bb',
    messagingSenderId: '1006888893410',
    projectId: 'lawbot-9770e',
    authDomain: 'lawbot-9770e.firebaseapp.com',
    storageBucket: 'lawbot-9770e.appspot.com',
    measurementId: 'G-P4HLHM3EFX',
  );
}
